### PR TITLE
update linear_homogenization.py: set option 'is_linear' to True for s…

### PR DESCRIPTION
**Pull request by vlukes**
…peed-up

### CODE REVIEW

**Comment by rc** [comment]
BTW. I am aware of the fact that this example is not covered by the tests, so I checked it manually. Note that MUMPS is not a required dependency, so using it as the solver here is a bit on the edge - there should be a fallback option.

**Comment by vlukes** [comment]
It was not the aim to change the solver in this example, I just forget to remove the line and uncomment the line with `scipy_direct`.

**Comment by vlukes** [comment]
...  just forgot to ...

**Comment by rc** [comment]
OK, now it's better :)

**Pull request merged**
