### PR TITLE
Update ev div grad terms

### PR DESCRIPTION
**Pull request by vlukes**

### CODE REVIEW

**Comment by rc** [comment]
Thanks! `python3 run_tests.py tests/test_term_call_modes.py` seems to fail on `de_grad`.

**Comment by vlukes** [comment]
> Thanks! `python3 run_tests.py tests/test_term_call_modes.py` seems to fail on `de_grad`.

Yes, I see. But I'm not able to identify the reason.

**Comment by rc** [comment]
I will have a look.

**Comment by rc** [comment]
I see, the `de_grad` term cannot have the weak mode, unlike `dw_div`. The results of the weak integral must be a scalar and this is not the case here. That is also why there is no `dw_grad` term.

**Comment by vlukes** [comment]
Thanks :)

**Review by rc — APPROVED** [review]

**Pull request merged**
