### PR TITLE
new example: simple modal analysis in declarative description

### PR DESCRIPTION
**Pull request by vlukes**
We are missing a simple modal analysis example. Here is the one in the declarative description.

### CODE REVIEW

**Comment by rc** [comment]
Thanks! Can you add the example also to `sfepy/tests/test_declarative_examples.py` and maybe add a nice custom view to the gallery script?

**Comment by rc** [comment]
BTW. I wonder maybe we should include a small but nice 3D mesh - the cylinder and box are kind of overused :)

**Comment by vlukes** [comment]
> BTW. I wonder maybe we should include a small but nice 3D mesh - the cylinder and box are kind of overused :)

Yes, it would nice! And do we have an interesting mesh?

**Comment by vlukes** [comment]
The last commit fixed the eigen solver convergence issues on macOS.

**Comment by rc** [comment]
Great! What will be good for the gallery? A single shape or several?

**Comment by rc** [comment]
I have added two commits in https://github.com/rc/sfepy/tree/modal_analysis_declarative - add those here, please (or modify as needed).

**Comment by rc** [comment]
> The first six frequencies calculated by **SfePy**: `[11.287, 11.317, 34.432, 80.709, 80.901, 93.144]` The results of modal analysis performed in **Ansys**: `[11.306, 11.316, 34.486, 80.901, 81.139, 93.472]`

Great agreement!

**Comment by vlukes** [comment]
> I have added two commits in https://github.com/rc/sfepy/tree/modal_analysis_declarative - add those here, please (or modify as needed).

OK, I have cherry-picked them.

**Pull request merged**
