### PR TITLE
fix presolve in homogenization

### PR DESCRIPTION
**Pull request by rc**
Hi @vlukes, I have removed presolving from the MiniAppBase, as it is done in Problem.solve() anyway. Further optimizations are possible, e.g. trying the presolve only if a direct solver is selected.

What do you say to replacing the iterative solvers?

### CODE REVIEW

**Comment by vlukes** [comment]
Instead of specifying  `'use_presolve': True`  in each example, I suggest setting `use_presolve` to `True` if `is_linear` in `coefs_base.init_solvers()`.

**Comment by rc** [comment]
The iterative linear solvers do not have this option. And I would rather not modify user settings - you might want to set use_presolve to False for debugging.

**Comment by vlukes** [comment]
> And I would rather not modify user settings - you might want to set use_presolve to False for debugging.

Yes, I agree. I thought to set `use_presolve` = True by default if not set by the user.

**Comment by rc** [comment]
The problem is that the value is bool with default False, so we do not have a way to distinguish the two situations: a user set False, a user did not set the option. We would need to modify the direct solvers...

**Comment by vlukes** [comment]
What about this in `coefs_base.init_solvers()`?

```
        if self.is_linear:
            for v in problem.conf.solvers.values():
                if v.kind.startswith('ls.'):
                    v.set_default('use_presolve', True)

        problem.set_conf_solvers(problem.conf.solvers, opts)
        problem.init_solvers()
        problem.set_linear(self.is_linear)
```

**Comment by vlukes** [comment]
Yes, now I see that there is an issue with iterative solvers ...

**Comment by rc** [comment]
OK, it introduces a complex magic, but we can try it. Note that, for correctors with a single linear system, using presolve and scipy_direct is actually a bit slower, as the matrix digest needs to be computed. What about the examples? I kind of like having it explicitly there.

**Comment by rc** [comment]
OK, it is there.

**Pull request merged**
