### PR TITLE
gen_gallery.py: support camera_position option in custom settings

### PR DESCRIPTION
**Pull request by rc**
... to be used in #909.

### CODE REVIEW

**Comment by rc** [comment]
Hey @vlukes does this work for you?

**Comment by vlukes** [comment]
> Hey @vlukes does this work for you?

Yes, I can run it and it generates figures. And the results are looking good.

**Comment by vlukes** [comment]
Perhaps this step `1. remove doc/examples/*::` in the docstring is no longer valid, right?

**Comment by rc** [comment]
> Perhaps this step `1. remove doc/examples/*::` in the docstring is no longer valid, right?

It serves for a clean-up of old/removed examples.

**Comment by vlukes** [comment]
> > Perhaps this step `1. remove doc/examples/*::` in the docstring is no longer valid, right?
> 
> It serves for a clean-up of old/removed examples.

OK, I see, `gen_gallery.py` generates `.rst` file into this. Figures are in `../doc/images/gallery`.

**Pull request merged**
