### PR TITLE
Fix biot c code

### PR DESCRIPTION
**Pull request by rc**
An error crept in with #347 ...

### CODE REVIEW

**Comment by rc** [comment]
@vlukes, does the fix work for you?

**Comment by vlukes** [comment]
@rc, could you rebase the fix-biot-ccode branch onto #346? Compilation seems to be all right. Sorry for the misplaced ";" in the C code.

**Comment by rc** [comment]
@vlukes, #346 is already merged in the master - this PR is on top of that.

**Comment by vlukes** [comment]
OK, my fault due to 'extra_dof' --> 'extra_dofs'. It works fine for me.

**Comment by rc** [comment]
OK, let us merge it then.

**Pull request merged**
