### PR TITLE
hyperelasticity on facet regions

### PR DESCRIPTION
**Pull request by rc**
Hi @vlukes, does this work for you?

### CODE REVIEW

**Comment by vlukes** [comment]
> Hi @vlukes, does this work for you?

Hi @rc, do you have a simple example that tests this functionality?

**Comment by rc** [comment]
Within sfepy I mostly used `pytest sfepy/tests/test_term_call_modes.py -vs`, but I have an outside example, where I evaluate a force on a surface.

**Comment by vlukes** [comment]
Yes, the tests pass on my computer.

Maybe the following deprecation warnings should be fixed. The last one is related to `terms_hyperelastic_tl.py` file.

```
sfepy/tests/test_term_call_modes.py: 306 warnings
  /home/vlukes/work/prog/sfepy/sfepy/terms/terms_multilinear.py:1173: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
  See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
    dtype = nm.find_common_type([op.dtype for op in operands[0]], [])

sfepy/tests/test_term_call_modes.py: 12 warnings
  /home/vlukes/work/prog/sfepy/sfepy/terms/terms_dot.py:536: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
    idx = int(material)

sfepy/tests/test_term_call_modes.py: 7290 warnings
  /home/vlukes/work/prog/sfepy/sfepy/terms/terms_hyperelastic_tl.py:131: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
    tan_mod[ii, jj, kk, ll] = 4 / 3 * exp * coef * (
```

**Comment by rc** [comment]
I will treat the warnings in another PR - for some reason I do not see any on my work computer, so I cannot be sure about the fixes :).

**Pull request merged**
