### PR TITLE
Updated sfepy-docker project

### PR DESCRIPTION
**Pull request by BubuLK**
Updated, simplified and optimized sfepy-docker images.

- updated doc/installation.rst instructions
- updated https://github.com/sfepy/sfepy-docker (sfepy-desktop added, old images removed)
- updated https://hub.docker.com/repositories/sfepy descriptions

Please do the following before accepting changes:

- test new image on Linux
- read/correct descriptions on GitHub & DockerHub

Feel free to cancel this "project" completly if you find it useless...

Thanks in advance for cooperation,
LK

### CODE REVIEW

**Comment by rc** [comment]
Great, thanks! Could you rebase your branch to the current master? I will test the images.

**Comment by rc** [comment]
I created  `docker-compose.yml`, did:
```
pip install docker docker-compose
docker-compose up -d
```
and got an error:
```
Traceback (most recent call last):
  File "~/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "~/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "~/.local/lib/python3.10/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "~/.local/lib/python3.10/site-packages/docker/transport/unixconn.py", line 27, in connect
    sock.connect(self.unix_socket)
PermissionError: [Errno 13] Permission denied

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.local/lib/python3.10/site-packages/requests/adapters.py", line 489, in send
    resp = conn.urlopen(
  File "~/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 787, in urlopen
    retries = retries.increment(
  File "~/.local/lib/python3.10/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "~/.local/lib/python3.10/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "~/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "~/.local/lib/python3.10/site-packages/urllib3/connectionpool.py", line 398, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "~/.local/lib/python3.10/site-packages/urllib3/connection.py", line 239, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "~/.local/lib/python3.10/site-packages/docker/transport/unixconn.py", line 27, in connect
    sock.connect(self.unix_socket)
urllib3.exceptions.ProtocolError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.local/lib/python3.10/site-packages/docker/api/client.py", line 214, in _retrieve_server_version
    return self.version(api_version=False)["ApiVersion"]
  File "~/.local/lib/python3.10/site-packages/docker/api/daemon.py", line 181, in version
    return self._result(self._get(url), json=True)
  File "~/.local/lib/python3.10/site-packages/docker/utils/decorators.py", line 46, in inner
    return f(self, *args, **kwargs)
  File "~/.local/lib/python3.10/site-packages/docker/api/client.py", line 237, in _get
    return self.get(url, **self._set_request_timeout(kwargs))
  File "~/.local/lib/python3.10/site-packages/requests/sessions.py", line 600, in get
    return self.request("GET", url, **kwargs)
  File "~/.local/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "~/.local/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "~/.local/lib/python3.10/site-packages/requests/adapters.py", line 547, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', PermissionError(13, 'Permission denied'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "~/.local/bin/docker-compose", line 8, in <module>
    sys.exit(main())
  File "~/.local/lib/python3.10/site-packages/compose/cli/main.py", line 81, in main
    command_func()
  File "~/.local/lib/python3.10/site-packages/compose/cli/main.py", line 200, in perform_command
    project = project_from_options('.', options)
  File "~/.local/lib/python3.10/site-packages/compose/cli/command.py", line 60, in project_from_options
    return get_project(
  File "~/.local/lib/python3.10/site-packages/compose/cli/command.py", line 152, in get_project
    client = get_client(
  File "~/.local/lib/python3.10/site-packages/compose/cli/docker_client.py", line 41, in get_client
    client = docker_client(
  File "~/.local/lib/python3.10/site-packages/compose/cli/docker_client.py", line 170, in docker_client
    client = APIClient(use_ssh_client=not use_paramiko_ssh, **kwargs)
  File "~/.local/lib/python3.10/site-packages/docker/api/client.py", line 197, in __init__
    self._version = self._retrieve_server_version()
  File "~/.local/lib/python3.10/site-packages/docker/api/client.py", line 221, in _retrieve_server_version
    raise DockerException(
docker.errors.DockerException: Error while fetching server API version: ('Connection aborted.', PermissionError(13, 'Permission denied'))
```
Any tips how to debug what is going on?

**Comment by BubuLK** [comment]
Dear Robert,

Python libraries for Docker Engine API are not needed at all, sorry
for possible confusion ;(

I recommend to start with validating your docker installation
as mentioned in SfePy docs (see https://docs.docker.com/engine/install/ubuntu/ for further details):


```
sudo apt-get update
sudo apt-get install ca-certificates curl gnupg
```

```
sudo install -m 0755 -d /etc/apt/keyrings
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
sudo chmod a+r /etc/apt/keyrings/docker.gpg
```

```
echo \
  "deb [arch="$(dpkg --print-architecture)" signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu \
  "$(. /etc/os-release && echo "$VERSION_CODENAME")" stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
```

```
sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
```

Add configuration to allow Docker to run without root privileges:

```
sudo groupadd docker
sudo usermod -aG docker $USER
```

And finally validate installation by running sample image:

`docker run --rm hello-world`

That's all...

Now should be 'docker compose' working...

LK

**Comment by rc** [comment]
Thanks, I knew there were some other instructions but did not find them. :) Now 
```
sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
```
lead to
```
Setting up docker-ce (5:24.0.4-1~ubuntu.22.04~jammy) ...
Job for docker.service failed because the control process exited with error code.
See "systemctl status docker.service" and "journalctl -xeu docker.service" for details.
invoke-rc.d: initscript docker, action "start" failed.
● docker.service - Docker Application Container Engine
     Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Fri 2023-07-21 16:35:09 CEST; 8ms ago
TriggeredBy: ● docker.socket
       Docs: https://docs.docker.com
    Process: 243883 ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock (code=exited, status=1/FAILURE)
   Main PID: 243883 (code=exited, status=1/FAILURE)
        CPU: 121ms
dpkg: error processing package docker-ce (--configure):
 installed docker-ce package post-installation script subprocess returned error exit status 1
Processing triggers for man-db (2.10.2-1) ...
Processing triggers for libc-bin (2.35-0ubuntu3.1) ...
Errors were encountered while processing:
 docker-ce
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
I re-run that command -> no errors, but then
```
docker run --rm hello-world

docker: permission denied while trying to connect to the Docker daemon socket at unix:///var/run/docker.sock: Post "http://%2Fvar%2Frun%2Fdocker.sock/v1.24/containers/create": dial unix /var/run/docker.sock: connect: permission denied.
See 'docker run --help'.
```
Sorry to be dense, more help needed :)

FWIW: my user is added to the docker group in `/etc/group`, but when running `groups`, docker is not listed there - do I need to reboot?
FWIW2: `sudo docker run --rm hello-world` seems to work.

**Comment by rc** [comment]
Forget the above comment, rebooting helped the group issue, no more sudo... :) Thanks!

Now I will check the docs and give you the feedback. I would mention that people should use the docker-engine and avoid the unofficial packages in the debian/ubuntu repositories, so that users do not mess up the installation like I did.

sfepy-desktop works for me! I would like to install pytest and ipython - can this be (easily) done?

**Comment by rc** [comment]
More  newbie questions (another screw up):
- I have tried to do `conda install pytest ipython`, and it failed.
- I have not properly updated PUID and PGID in `docker-compose.yml` - I have removed my docker directory, but re-running the docker-compose command does not download anything, only copies some files from somewhere :) How do I purge everything and start again from a clean slate?

**Comment by rc** [comment]
Thanks for the explanation, it is clearer now. BTW. I had to do `docker image rm sfepy-desktop` to get the updated image downloaded - `docker compose up -d` just started the old image.

Thanks for adding the packages - now I can run `sfepy-test` and all tests pass.

You are right, installing packages worked also before, I had used only `sudo` and not `sudo -i` which is required with conda (otherwise the command is not on the PATH).

Can I rebase the branch onto the current git master and push it here?

**Comment by BubuLK** [comment]
Add image update: my fault, sorry 😢
There are some auto-tools, but simplest way is to run 'docker pull <image>' if you want to update.

Sorry for confusion 😢

**Comment by rc** [comment]
So I finally got to the rebase and force-pushed it here. So `git fetch` + reset, not `git pull`, otherwise you get unwanted merges. I also did some small fixes in the doc.

**Comment by BubuLK** [comment]
Many thanks and sorry for my ignorance ;(

**Comment by rc** [comment]
My docker ignorance is way bigger ;) Let us merge this!

For future - do you think it might be useful to list the basic docker commands + add some of the info you have written in this PR to sfepy docs? I am not a regular docker user, so I always struggle with the elementary commands.

**Comment by rc** [comment]
Yes, I am for linking to good external docs - so some common use cases with links to more specific docs  would do it, just like you say. No need to copy paste docker documentation.

Possible use cases (= specific links):
- how to install docker on ubuntu flavors / mac / windows
- how to get an image for the first time
- how to refresh it
- how to nuke it

What do you think?

Essentially, I am a total docker noob, so others like me can have similar troubles, and no desire to read through the very good but extensive and hierarchical docker docs. :)

**Pull request merged**
