### PR TITLE
Volume/surface terms clean-up

### PR DESCRIPTION
**Pull request by vlukes**
This PR unifies volume/surface terms. If the term integration is set to `'by_region'` then the integration mode, i.e. `'volume'`, `'surface'`, is determined by `term.region.kind`.  The term attribute `'surface_integration'` allows to set `'surface_extra'` integration for surface regions.

The following terms are renamed/changed:

- `dw_volume_dot` --> `dw_dot`
- `dw_surface_dot` --> `dw_dot`
- `ev_volume_integrate` --> `ev_integrate`
- `ev_surface_integrate` --> `ev_integrate`
- `ev_volume_integrate_mat` --> `ev_integrate_mat`
- `ev_surface_integrate` --> `ev_integrate_mat`
- `dw_volume_integrate` --> `dw_integrate`
- `dw_surface_integrate` --> `dw_integrate`
- `d_volume` -->  `d_region`  __I'm not sure by the name!__
- `d_surface` --> `d_region`
- `ev_cauchy_strain_s` -->  `ev_cauchy_strain`
- `ev_surface_grad` --> `ev_grad`
- `ev_surface_div` --> `ev_div`

For backward compatibility, the old term names are defined in `terms_compat.py`.

### CODE REVIEW

**Comment by vlukes** [comment]
Update:

- d_volume, d_surface  --> ev_volume
- `\int_{R} ...` replaced by `\int_{\cal{D}}`, user's guide updated

**Comment by rc** [comment]
Thanks! Did you update also the multilinear terms and their use in examples/navier_stokes/stokes_slip_bc.py?

**Comment by vlukes** [comment]
> Thanks! Did you update also the multilinear terms and their use in examples/navier_stokes/stokes_slip_bc.py?

Done.

**Comment by rc** [comment]
Great! Few more details: I tried `git grep dw_volume`, and found occurrences in `doc/developer_guide.rst` and a single occurrence in `doc/users_guide.rst`.

`git grep ev_volume` -> `doc/users_guide.rst`
`git grep d_volume` ->  `tests/test_volume.py`

Otherwise all seems well replaced.

**Comment by vlukes** [comment]
- `doc/developer_guide.rst` - updated
- `doc/users_guide.rst` - fixed
- `tests/test_volume.py` - there is `d_volume_surface`, will be renamed in the next PR

**Review by rc — APPROVED** [review]

**Pull request merged**
