### PR TITLE
Allow empty dict in dict_from_string

### PR DESCRIPTION
**Pull request by lokik**

### CODE REVIEW

**Comment by rc** [comment]
Thanks!

I get:
```
    cvt_dict = lambda toks: dict(toks.asList())
ValueError: dictionary update sequence element #0 has length 1; 2 is required
```
with your solution. The following works (and is the only change necessary):
```
cvt_dict = lambda toks: dict([tok if len(tok) == 2 else tok + [{}]
                              for tok in toks.asList()])
 ```

Could you verify that?

**Comment by lokik** [comment]
Hi,
In my environment your fix does not work and mine does :-) Do we talk about the same bug? 
Matyáš

novakmat@thsun54a ~/q/sfepy (detached*)*$ cat t.py
from sfepy.base.conf import dict_from_string
print(dict_from_string(''))

novakmat@thsun54a ~/q/sfepy (detached*)*$ git checkout 5dc49ce02873dc610b9161b2c408b64b34dd3538
M	Makefile
HEAD is now at 5dc49ce0 Allow empty dict in dict_from_string
novakmat@thsun54a ~/q/sfepy (detached*)*$ p t.py
{}

novakmat@thsun54a ~/q/sfepy (detached*)*$ git checkout origin/master
M	Makefile
Previous HEAD position was 5dc49ce0 Allow empty dict in dict_from_string
HEAD is now at a40a9c29 Merge branch 'update-ntc-links'
>>> (possible modification of sfepy/base/parse_conf via your recipe) <<<
novakmat@thsun54a ~/q/sfepy (detached*)*$ p t.py
Traceback (most recent call last):
  File "t.py", line 3, in <module>
    print(dict_from_string(''))
  File "/home/novakmat/13duben/sfepy/sfepy/base/conf.py", line 282, in dict_from_string
    for r in parser.parseString(string, parseAll=True):
  File "/usr/lib/python3.6/site-packages/pyparsing.py", line 1632, in parseString
    raise exc
  File "/usr/lib/python3.6/site-packages/pyparsing.py", line 1622, in parseString
    loc, tokens = self._parse( instring, 0 )
  File "/usr/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/lib/python3.6/site-packages/pyparsing.py", line 3378, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/lib/python3.6/site-packages/pyparsing.py", line 3717, in parseImpl
    return self.expr._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/lib/python3.6/site-packages/pyparsing.py", line 3378, in parseImpl
    loc, resultlist = self.exprs[0]._parse( instring, loc, doActions, callPreParse=False )
  File "/usr/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/lib/python3.6/site-packages/pyparsing.py", line 3545, in parseImpl
    raise maxException
  File "/usr/lib/python3.6/site-packages/pyparsing.py", line 3530, in parseImpl
    ret = e._parse( instring, loc, doActions )
  File "/usr/lib/python3.6/site-packages/pyparsing.py", line 1379, in _parseNoCache
    loc,tokens = self.parseImpl( instring, preloc, doActions )
  File "/usr/lib/python3.6/site-packages/pyparsing.py", line 2469, in parseImpl
    raise ParseException(instring, loc, self.errmsg, self)
pyparsing.ParseException: Expected {"None" | "True" | "False" | {real 'j'} | real | integer | Forward: ... | Forward: ... | Forward: ... | quotedString using single or double quotes | W:(ABCD...,ABCD...)} (at char 0), (line:1, col:1)

**Comment by rc** [comment]
Yes, try `print(dict_from_string('something={}'))`. But the thing you fixed is also useful :)

**Comment by rc** [comment]
Fixed by #485, closing...

**Pull request closed without merging**
