### PR TITLE
Include example Docker compose file for simplicity

### PR DESCRIPTION
**Pull request by brylie**
Trying to make it easier to get started developing with SfePy.

### CODE REVIEW

**Comment by rc** [comment]
Thank you, @brylie!

I did:
```
docker pull sfepy/sfepy-notebook

pip install --user docker-compose
# created docker-compose.yml 
docker-compose up
```

and got

```
Recreating sfepy_container ... done
Attaching to sfepy_container
sfepy_container | [I 2021-10-04 20:48:21.086 ServerApp] jupyterlab | extension was successfully linked.
sfepy_container | [W 2021-10-04 20:48:21.089 NotebookApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
sfepy_container | [W 2021-10-04 20:48:21.089 NotebookApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
sfepy_container | [W 2021-10-04 20:48:21.089 NotebookApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
sfepy_container | [W 2021-10-04 20:48:21.089 NotebookApp] 'terminado_settings' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
sfepy_container | [W 2021-10-04 20:48:21.096 ServerApp] [Errno 13] Permission denied: '/home/sfepy/.local'
sfepy_container | Traceback (most recent call last):
sfepy_container |   File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 535, in get
sfepy_container |     value = obj._trait_values[self.name]
sfepy_container | KeyError: 'runtime_dir'
sfepy_container | 
sfepy_container | During handling of the above exception, another exception occurred:
sfepy_container | 
sfepy_container | Traceback (most recent call last):
sfepy_container |   File "/opt/conda/bin/jupyter-lab", line 10, in <module>
sfepy_container |     sys.exit(main())
sfepy_container |   File "/opt/conda/lib/python3.8/site-packages/jupyter_server/extension/application.py", line 518, in launch_instance
sfepy_container |     serverapp = cls.initialize_server(argv=args)
sfepy_container |   File "/opt/conda/lib/python3.8/site-packages/jupyter_server/extension/application.py", line 488, in initialize_server
sfepy_container |     serverapp.initialize(
sfepy_container |   File "/opt/conda/lib/python3.8/site-packages/traitlets/config/application.py", line 87, in inner
sfepy_container |     return method(app, *args, **kwargs)
sfepy_container |   File "/opt/conda/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 2050, in initialize
sfepy_container |     self.init_configurables()
sfepy_container |   File "/opt/conda/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 1493, in init_configurables
sfepy_container |     connection_dir=self.runtime_dir,
sfepy_container |   File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 575, in __get__
sfepy_container |     return self.get(obj, cls)
sfepy_container |   File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 538, in get
sfepy_container |     default = obj.trait_defaults(self.name)
sfepy_container |   File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 1578, in trait_defaults
sfepy_container |     return self._get_trait_default_generator(names[0])(self)
sfepy_container |   File "/opt/conda/lib/python3.8/site-packages/jupyter_core/application.py", line 85, in _runtime_dir_default
sfepy_container |     ensure_dir_exists(rd, mode=0o700)
sfepy_container |   File "/opt/conda/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 11, in ensure_dir_exists
sfepy_container |     os.makedirs(path, mode=mode)
sfepy_container |   File "/opt/conda/lib/python3.8/os.py", line 213, in makedirs
sfepy_container |     makedirs(head, exist_ok=exist_ok)
sfepy_container |   File "/opt/conda/lib/python3.8/os.py", line 213, in makedirs
sfepy_container |     makedirs(head, exist_ok=exist_ok)
sfepy_container |   File "/opt/conda/lib/python3.8/os.py", line 213, in makedirs
sfepy_container |     makedirs(head, exist_ok=exist_ok)
sfepy_container |   File "/opt/conda/lib/python3.8/os.py", line 223, in makedirs
sfepy_container |     mkdir(name, mode)
sfepy_container | PermissionError: [Errno 13] Permission denied: '/home/sfepy/.local'
sfepy_container exited with code 1
```

Do you have an idea what am I doing wrong? (Docker newbie here...)

**Comment by brylie** [comment]
What happens if you just run `docker-compose up` without the other commands? E.g. don't run these

```
docker pull sfepy/sfepy-notebook

pip install --user docker-compose
```

**Comment by rc** [comment]
Without the second I do not have the `docker-compose` command (I could have used `apt install ...` but the version seemed old).

I tried removing all old containers and images, then:
```
$ docker-compose up
Pulling sfepy (sfepy/sfepy-notebook:)...
ERROR: Head https://registry-1.docker.io/v2/sfepy/sfepy-notebook/manifests/latest: Get https://auth.docker.io/token?scope=repository%3Asfepy%2Fsfepy-notebook%3Apull&service=registry.docker.io: net/http: TLS handshake timeout
```

**Comment by brylie** [comment]
Might you be experiencing an issue similar to the following?

- https://serverfault.com/a/913384

**Comment by rc** [comment]
Maybe. The manual `docker pull sfepy/sfepy-notebook` leads to the same error, even thought it worked yesterday. I guess I will wait it over,  there might be some network problems (normally it's very fast).

**Comment by rc** [comment]
I have used one of the tricks mentioned in the link you found, with the same result as the manual pull:
```
$ docker-compose up || docker-compose up || docker-compose up || docker-compose up || docker-compose up 
Pulling sfepy (sfepy/sfepy-notebook:)...
ERROR: Get https://registry-1.docker.io/v2/: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
Pulling sfepy (sfepy/sfepy-notebook:)...
latest: Pulling from sfepy/sfepy-notebook
c549ccf8d472: Pull complete
0d603422d600: Pull complete
d2d6f7871b14: Pull complete
ef11d33a64bb: Pull complete
4f4fb700ef54: Pull complete
61ad8e2f5e1a: Pull complete
affee577f183: Pull complete
Digest: sha256:f850e08a70c4a923a1d3dd6863679f6223491d74e1851c6dde6b490177568d0e
Status: Downloaded newer image for sfepy/sfepy-notebook:latest
Creating sfepy_container ... done
Attaching to sfepy_container
sfepy_container | [I 2021-10-05 08:56:49.881 ServerApp] jupyterlab | extension was successfully linked.
sfepy_container | [W 2021-10-05 08:56:49.883 NotebookApp] 'ip' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
sfepy_container | [W 2021-10-05 08:56:49.883 NotebookApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
sfepy_container | [W 2021-10-05 08:56:49.883 NotebookApp] 'port' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
sfepy_container | [W 2021-10-05 08:56:49.883 NotebookApp] 'terminado_settings' has moved from NotebookApp to ServerApp. This config will be passed to ServerApp. Be sure to update your config before our next release.
sfepy_container | [W 2021-10-05 08:56:49.890 ServerApp] [Errno 13] Permission denied: '/home/sfepy/.local'
sfepy_container | Traceback (most recent call last):
sfepy_container |   File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 535, in get
sfepy_container |     value = obj._trait_values[self.name]
sfepy_container | KeyError: 'runtime_dir'
sfepy_container | 
sfepy_container | During handling of the above exception, another exception occurred:
sfepy_container | 
sfepy_container | Traceback (most recent call last):
sfepy_container |   File "/opt/conda/bin/jupyter-lab", line 10, in <module>
sfepy_container |     sys.exit(main())
sfepy_container |   File "/opt/conda/lib/python3.8/site-packages/jupyter_server/extension/application.py", line 518, in launch_instance
sfepy_container |     serverapp = cls.initialize_server(argv=args)
sfepy_container |   File "/opt/conda/lib/python3.8/site-packages/jupyter_server/extension/application.py", line 488, in initialize_server
sfepy_container |     serverapp.initialize(
sfepy_container |   File "/opt/conda/lib/python3.8/site-packages/traitlets/config/application.py", line 87, in inner
sfepy_container |     return method(app, *args, **kwargs)
sfepy_container |   File "/opt/conda/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 2050, in initialize
sfepy_container |     self.init_configurables()
sfepy_container |   File "/opt/conda/lib/python3.8/site-packages/jupyter_server/serverapp.py", line 1493, in init_configurables
sfepy_container |     connection_dir=self.runtime_dir,
sfepy_container |   File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 575, in __get__
sfepy_container |     return self.get(obj, cls)
sfepy_container |   File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 538, in get
sfepy_container |     default = obj.trait_defaults(self.name)
sfepy_container |   File "/opt/conda/lib/python3.8/site-packages/traitlets/traitlets.py", line 1578, in trait_defaults
sfepy_container |     return self._get_trait_default_generator(names[0])(self)
sfepy_container |   File "/opt/conda/lib/python3.8/site-packages/jupyter_core/application.py", line 85, in _runtime_dir_default
sfepy_container |     ensure_dir_exists(rd, mode=0o700)
sfepy_container |   File "/opt/conda/lib/python3.8/site-packages/jupyter_core/utils/__init__.py", line 11, in ensure_dir_exists
sfepy_container |     os.makedirs(path, mode=mode)
sfepy_container |   File "/opt/conda/lib/python3.8/os.py", line 213, in makedirs
sfepy_container |     makedirs(head, exist_ok=exist_ok)
sfepy_container |   File "/opt/conda/lib/python3.8/os.py", line 213, in makedirs
sfepy_container |     makedirs(head, exist_ok=exist_ok)
sfepy_container |   File "/opt/conda/lib/python3.8/os.py", line 213, in makedirs
sfepy_container |     makedirs(head, exist_ok=exist_ok)
sfepy_container |   File "/opt/conda/lib/python3.8/os.py", line 223, in makedirs
sfepy_container |     mkdir(name, mode)
sfepy_container | PermissionError: [Errno 13] Permission denied: '/home/sfepy/.local'
sfepy_container exited with code 1
```

**Comment by brylie** [comment]
From what directory are you running these commands? Try running the command from a new directory? I.e. the permissions error may be related to subfolders of your home directory, if you are running the commands from within home.

**Comment by rc** [comment]
Yes, I have created a new directory, where I put the `docker-compose.yml` file (the only file in there). Anyway, `/home/sfepy/.local` is surely a directory in the container/image - it is not on my machine. Do I need to run the command with `sudo`? BTW:
```
$ docker-compose -v
docker-compose version 1.29.2, build unknown
$ docker -v
Docker version 20.10.7, build 20.10.7-0ubuntu1~20.04.2
```

**Comment by brylie** [comment]
The Docker Compose file is creating a directory mapping from the local folder (where running `docker-compose up`) to the `/home/sfepy/` directory within the container. 

```yaml
       volumes:
        # map the current directory to the sfepy home directory within the container
         - .:/home/sfepy/
```

The reason for the directory mapping is so that you can access the Python notebooks from your local computer and they will persist if you stop the Docker container.

**Comment by brylie** [comment]
Try the following steps:

```sh
$ docker system prune -a
$ mkdir temporary
$ cd temporary
```

Then, add the `docker-compose.yml` file to the `tempoarary/` directory and run `docker-compose up`.

**Comment by brylie** [comment]
I've updated the `docker-compose.yml` to use a `code/` subdirectory within the `sfepy` home directory:

```yaml
version: "3"
services:
  sfepy:
    container_name: sfepy_container
    image: sfepy/sfepy-notebook
    command: jupyter lab
    volumes:
      - .:/home/sfepy/
    ports:
      - "8888:8888"
```

**Comment by rc** [comment]
It seems to work, great!

**Pull request merged**
