### PR TITLE
optionally report (nonlinear) solver status

### PR DESCRIPTION
**Pull request by rc**
... it's grepable.

### CODE REVIEW

**Review by vlukes — APPROVED** [review]
Great!

**Comment by vlukes** [comment]
It would be nice to  have a summary status at the end as well.

e.g:
```
sfepy: solved in 11 steps in 4.48 seconds
  step: 1, iter: 5,  ls_iter: -1, err: 9.41468500e-09
  step: 2, iter: 8,  ls_iter: -1, err: 5.67564700e-09
  ...
  step: 11, ...
  residual: 2.00854370 [s]
    matrix: 15.02511080 [s]
     solve: 0.00711482 [s]
```

**Comment by rc** [comment]
Yes. That would belong to either a time-stepper or we could accumulate the time stats in `poststep_fun()` of `get_tss_functions()`.

**Comment by rc** [comment]
I have an idea...

**Comment by rc** [comment]
The totals are now printed after the problem solution.

**Review by vlukes — APPROVED** [review]
:+1:

**Comment by rc** [comment]
It fails with adaptive time-stepping as the rejected steps are not counted. It will be fixed soon.

**Comment by rc** [comment]
More magic...

**Pull request merged**
