### PR TITLE
update homogenization engine to allow saving "pi" correctors

### PR DESCRIPTION
**Pull request by vlukes**

### CODE REVIEW

**Comment by rc** [comment]
Thanks, is it tested in some example?

**Comment by vlukes** [comment]
It is tested in `linear_homogenization.py`.

**Comment by rc** [comment]
@vlukes, I do not see `'save_name'` set for `'pis'`, and if I do set it, I do not see any field in the resulting file - what am I doing wrong?

**Comment by vlukes** [comment]
It is tested in `linear_homogenization.py`.

**Comment by vlukes** [comment]
Look at `examples/homogenization/linear_homogenization.py` again, lines 156-157. I changed it later.

**Comment by rc** [comment]
I see, thanks!

**Comment by rc** [comment]
Now `test_install.py` fails:

```
python2 examples/homogenization/rs_correctors.py -n
```

**Comment by vlukes** [comment]
setup_output() has to be called in `rs_correctors.py`. Fixed.

**Comment by rc** [comment]
Thanks!

**Pull request merged**
