### PR TITLE
update LinearPrestressTerm: allow for non-symmetric form

### PR DESCRIPTION
**Pull request by vlukes**

### CODE REVIEW

**Comment by rc** [comment]
Thanks!

There are some problems as tests/test_term_call_modes.py fails with:
```
build_nonsym_grad(): ERR_Switch
```
 I would say that `build_nonsym_grad()` needs to be updated for 1D in the switch? Lots of terms seem to be failing in 1D now:
```
... failed: [('domain_/meshes/elements/1_2_2', 'dw_lin_prestress'), ('domain_/meshes/elements/1_2_2', 'dw_lin_strain_fib'), ('domain_/meshes/elements/1_2_2', 'dw_piezo_coupling'), ('domain_/meshes/elements/1_2_2', 'dw_s_dot_grad_i_s'), ('domain_/meshes/elements/1_2_2', 'dw_s_dot_mgrad_s'), ('domain_/meshes/elements/1_2_2', 'dw_st_adj1_supg_p'), ('domain_/meshes/elements/1_2_2', 'dw_st_adj2_supg_p'), ('domain_/meshes/elements/1_2_2', 'dw_st_adj_supg_c'), ('domain_/meshes/elements/1_2_2', 'dw_st_grad_div'), ('domain_/meshes/elements/1_2_2', 'dw_st_pspg_c'), ('domain_/meshes/elements/1_2_2', 'dw_st_pspg_p'), ('domain_/meshes/elements/1_2_2', 'dw_st_supg_c'), ('domain_/meshes/elements/1_2_2', 'dw_st_supg_p'), ('domain_/meshes/elements/1_2_2', 'dw_stokes'), ('domain_/meshes/elements/1_2_2', 'dw_tl_bulk_active')]
--- test_term_call_modes: failed!
```

**Comment by vlukes** [comment]
Yes, I see. Fixed now.

**Comment by rc** [comment]
Thanks! BTW. why was the code of `build_nonsym_grad()` moved? It is not easy to see if it was actually changed or not.

**Comment by vlukes** [comment]
`build_nonsym_grad()` should be defined before `dw_lin_prestress()`, so one of them must be moved.

**Comment by rc** [comment]
That is not necessary - just put the function into the header file. Then the order is not important.

**Comment by rc** [comment]
But maybe logically the move makes sense... :)

**Comment by rc** [comment]
Or better: a move into form_sdcc.[ch] makes sense...

**Comment by vlukes** [comment]
OK, it can be moved into `form_sdcc`.

**Pull request merged**
