### PR TITLE
resview.py: unify camera position handling in animation and normal modes

### PR DESCRIPTION
**Pull request by rc**
Hi @vlukes, this PR is sort of related to #918 - I struggled to get a correct camera setting for a 2D mesh, and on the way I made the changes presented here.

The still remaining problems are:
- The 'c' key does not work for meshes with no z component. (Hence #918 workaround.)
- The animation saving works only with --off-screen and for some inputs it leads to infinite
 ```
Error in sys.excepthook:

Original exception was:
Error in sys.excepthook:

Original exception was:
...
```
No idea why, maybe it's just my installation.

### CODE REVIEW

**Comment by vlukes** [comment]
> * The 'c' key does not work for meshes with no z component.

What do you mean by "does not work"?

When I run  `resview.py meshes/2d/square_tri2.mesh -2` and press 'c' I get

```
--camera-position="0,0,5.4641,0,0,0,0,1,0"
```

For `resview.py meshes/2d/square_tri2.mesh` the output is

```
--camera-position="-3.03561,-3.03561,1.15031,0,0,0,0,0,1"
```

**Comment by vlukes** [comment]
> * The animation saving works only with --off-screen and for some inputs it leads to infinite.

Yes, there is something wrong. I will check.

**Comment by rc** [comment]
> > * The 'c' key does not work for meshes with no z component.
> 
> What do you mean by "does not work"?

I press `c` and nothing happens.
 
> When I run `resview.py meshes/2d/square_tri2.mesh -2` and press 'c' I get
> 
> ```
> --camera-position="0,0,5.4641,0,0,0,0,1,0"
> ```
> 
> For `resview.py meshes/2d/square_tri2.mesh` the output is
> 
> ```
> --camera-position="-3.03561,-3.03561,1.15031,0,0,0,0,0,1"
> ```

Those two work for me as well. I am attaching the mesh that does not. However, the same mesh with saved regions is OK. So it might be related to a presence of  vector variables?
[i919.vtk.gz](https://github.com/sfepy/sfepy/files/10332936/i919.vtk.gz)

**Comment by vlukes** [comment]
> Those two work for me as well. I am attaching the mesh that does not. However, the same mesh with saved regions is OK. So it might be related to a presence of vector variables?
> [i919.vtk.gz](https://github.com/sfepy/sfepy/files/10332936/i919.vtk.gz)

It works for me, `resview.py i919.vtk` and pressed `c` gives:

```
mesh from i919.vtk:
  points:  10201
  cells:   10000
  bounds:  [(-0.0025, 0.0025), (-0.0025, 0.0025), (0.0, 0.0)]
  scalars: node_groups, mat_id
  vectors: u, v, a
  steps:   1
/home/vlukes/work/prog/sfepy/./resview.py:374: RuntimeWarning: divide by zero encountered in double_scalars
  scale = mesh_size * 0.15 / nm.linalg.norm(fval, axis=1).max()
/home/vlukes/.local/lib/python3.10/site-packages/pyvista/core/pointset.py:205: PyvistaDeprecationWarning: You did not specify a value for `inplace` and the default value will be changing to `False` in future versions for point-based meshes (e.g., `PolyData`). Please make sure you are not assuming this to be an inplace operation.
  warnings.warn(DEFAULT_INPLACE_WARNING, PyvistaDeprecationWarning)
plot 0: u_magnitude(step 0); u_magnitude(step 0):glyphs=u, factor=1.00e+00
plot 1: v_magnitude(step 0); v_magnitude(step 0):glyphs=v, factor=7.50e-04
plot 2: a_magnitude(step 0); a_magnitude(step 0):glyphs=a, factor=1.00e+00
--camera-position="-0.0333917,-0.0333917,0.0126534,-0.00092,0.0075,0,0,0,1"
```

**Comment by rc** [comment]
So it's a quirk in my pyvista installation.

**Comment by rc** [comment]
So, do you agree with the proposed changes, assuming the animation fixes would go to another PR?

**Comment by vlukes** [comment]
Yes, merge it.

**Pull request merged**
