### PR TITLE
new surface term (term name?)

### PR DESCRIPTION
**Pull request by vlukes**
I think we don't have a term that does the same job as the one in this PR. @rc, do you have an idea how to name this surface term?

### CODE REVIEW

**Comment by rc** [comment]
Yes, it is not available. What is the context of its use? It seems like a flux but it is tested by a vector variable,

**Comment by vlukes** [comment]
Surface traction in Stokes flow:

\int \ul{v} \cdot (\ull{\sigma} cdot \ul{n})

where

\sigma = - p I + \nu \nabla \ul{u}

If p is given, than the second term (new one in PR) will appear on the LHS.

**Comment by rc** [comment]
So what about `StokesTractionTerm` and `de_stokes_traction`? Your explanation above could be added to the docstring.

**Comment by rc** [comment]
Thanks, LGTM!

**Pull request merged**
