### PR TITLE
update meshio.py: support for msh file format (gmsh) - reading

### PR DESCRIPTION
**Pull request by vlukes**

### CODE REVIEW

**Comment by rc** [comment]
Thank you!

Could you add a small example mesh to 'meshes/various_formats/' and update 'tests/test_meshio.py'?

**Comment by vlukes** [comment]
The new test meshes (MSH) are there.

**Comment by rc** [comment]
When viewing the 3D mesh with

```
./postproc.py --wire meshes/various_formats/msh_tetra.msh
```

The edges between domains seem doubled - is the mesh connected correctly?

**Comment by vlukes** [comment]
Yes, there are doubled vertices at the interface of two material groups, it is just a mesh for testing purpose. Does it matter?

**Comment by rc** [comment]
I would prefer a mesh that would work for a simulation.

**Comment by vlukes** [comment]
OK, I pushed the new one.

**Comment by rc** [comment]
The new one seems to be in VTK format, not gmsh?

**Comment by vlukes** [comment]
Sorry, my fault, corrected.

**Comment by rc** [comment]
Thanks you, the mesh is OK now.

I have just noticed that the both calls to `_read_bounding_box()` are wrong - they do not obey the values of `ret_fd`, `ret_dim` arguments to `MeshIO.read_bounding_box()`.

**Comment by vlukes** [comment]
Calls to _read_bounding_box() - fixed.

**Comment by rc** [comment]
Thanks!

**Pull request merged**
