### PR TITLE
Fix splinebox

### PR DESCRIPTION
**Pull request by vlukes**

### CODE REVIEW

**Comment by rc** [comment]
Thanks!

Could you remove the 'update coeffficients.py' commit (it is in #471, right?)
How does the new code behave with NumPy < 1.14.0?

**Comment by rc** [comment]
Also why does tests/test_homogenization_perfusion.py fail in Python 3?

**Comment by vlukes** [comment]
'update coeffficients.py' commit is removed.

**Comment by rc** [comment]
The problem disappeared, let's merge this :)

**Comment by rc** [comment]
Yes a fix is needed, the current version of calling `lstsq()` does not work with numpy 1.13.3.

**Pull request merged**
