### PR TITLE
allow matrix_hook to handle residual vector

### PR DESCRIPTION
**Pull request by vlukes**

### CODE REVIEW

**Comment by rc** [comment]
OK! Just add it also to LCBCEvaluator.eval_residual() with mode 'lcbc_residual'(?).

**Comment by vlukes** [comment]
LCBCEvaluator.eval_residual() calls BasicEvaluator.eval_residual() so the matrix_hook is processed.

**Comment by rc** [comment]
Yes, but the two get a different vector - before and after LCBC application- see .eval_tangent_matrix().

**Comment by vlukes** [comment]
Done, LCBCEvaluator.eval_residual() calls matrix_hook with mode 'lcbc_residual' now.

**Pull request merged**
