### PR TITLE
lib.lapack bug fix

### PR DESCRIPTION
**Pull request by RexFuzzle**
As per http://docs.scipy.org/doc/scipy/reference/release.0.12.0.html#scipy-lib-lapack lib.lapack is depreciated and so I updated to the new linalg.

### CODE REVIEW

**Comment by rc** [comment]
Thank you!

In order to make it work with older SciPy versions, could you make that conditional, based on ``scipy.__version__``?

**Comment by RexFuzzle** [comment]
Cool, will get on it next week.

**Comment by rc** [comment]
OK, thanks!

**Comment by RexFuzzle** [comment]
So it looks like scipy hasn't been imported before this point and to get the version you have to import scipy- seems a bit unnecesary to import scipy just to get the version. I can do a try else instead?

**Comment by rc** [comment]
OK, that would do: try the new version, and on exception revert to the old one.

**Comment by rc** [comment]
Looks good. Only, please, squash the three commits to a single one (message something like "fix lib.lapack import"). I will then merge it. Thank you!

PS: The easiest way to do that is IMHO to reset the branch back and create a new single commit with the try-except method.

**Comment by rc** [comment]
Final nit-picking: "Bug lib.lapack.bug fix" -> "lib.lapack import bug fix" :)

**Comment by rc** [comment]
Sorry, I commented to the now-removed commit, so you probably missed that: It is recommended by Python gurus to catch a specific exception rather than all, so here, use `except ImportError:`, please. (I apologize for being pesky.)

**Comment by rc** [comment]
Thank you, it is merged.

**Pull request merged**
