### PR TITLE
Update for multiscale simulations of  large deformations

### PR DESCRIPTION
**Pull request by vlukes**
main changes:
 - solving multiple micro-problems in "one step", micro configurations are updated using the macroscopic deformation gradient and correctors
 - the volumes required in computation of coefficients are now computed also as coefficients - can be easily parallelized
 - caching of periodic matches (deformed microstructures are no more periodic)
 - improved parallelization mechanism, new multiproc.py module
 - using global caches for periodic matches and (some) mappings

### CODE REVIEW

**Comment by rc** [comment]
Great job! I have just a few remarks:

- [ ]  sfepy/discrete/fem/periodic.py needs a clean-up (spaces around function args)
- [ ] ``match_coors()``: ``coor1`` -> ``coors1``, ``which`` is undefined.
- [ ] I wonder if there is a better place to initialize ``domain.mesh.coors_act`` than ``set_mesh_coors()``?
- [ ] add into sfepy/base/multiproc.py:

```
managers; Process; # Make pyflakes happy.
```
- [ ] document sfepy/base/multiproc.py and the new functions in engine.py etc. (e.g. ``calculate_req()`` has tons of arguments)
- [ ] remove line 157 in engine.py
- [ ] unused imports (output, MiniAppBase, six), unused line 98 in sfepy/homogenization/homogen_app.py
- [ ] Why using capitals for VOLUME coefficients?  What about "'Volume'"?

**Comment by vlukes** [comment]
Yes, there could be a better place to initialize 'domain.mesh.coors_act'. But the other solutions require some extra options or major changes in the code. Now, I'm not sure how to make it better.

All other remarks have been reflected in the commits.

**Comment by rc** [comment]
OK, thanks! Is there a (simple) way of testing the large deformation homogenization besides running the full example? (Something in terms of ``tests/test_homogenization_engine.py``).

**Comment by vlukes** [comment]
I have updated tests/test_homogenization_engine.py to test the functions 
related to splitting into chunks, merging chunks and volume computation. 
Could it be like this?

**Comment by rc** [comment]
Seems good! Merging soon...

**Pull request merged**
