### PR TITLE
Constant materials

### PR DESCRIPTION
**Pull request by vlukes**
Material parameters with constant value are now created with shape (1, nqp, n, m).

### CODE REVIEW

**Comment by rc** [comment]
Thanks!

I have just a few remarks:
- I propose renaming `mat_constant` argument of `ConstantFunction` to `ret_constant`, or `no_tile`.  Functions are not used only for evaluating materials.
- Not sure about placement of `make_full_mat_array()` - what about making it a static method of Term? And/or rename it to `tile_mat()`?
- `ETermBase` needs also full sizes of materials -> `ExpressionArg` should do it.

**Comment by vlukes** [comment]
> Thanks!
> 
> I have just a few remarks:
> 
>     * I propose renaming `mat_constant` argument of `ConstantFunction` to `ret_constant`, or `no_tile`.  Functions are not used only for evaluating materials.
>

OK, argument renamed to `no_tile`.
 
>     * Not sure about placement of `make_full_mat_array()` - what about making it a static method of Term? And/or rename it to `tile_mat()`?
> 

I have moved the function into `Term` class as `tile_mat()` static method.

>     * `ETermBase` needs also full sizes of materials -> `ExpressionArg` should do it.

Is it really needed? Are there tests for the multilinear terms?

**Comment by vlukes** [comment]
> Previously, the tests/test_term_call_modes.py test failed on einsums, now it passes. Actually einsum should support bradcasting, so it may work?

Yes, einsum support broadcasting so I think it should work.

**Comment by rc** [comment]
I do not see `no_tile` in the sources?

**Comment by vlukes** [comment]
> I do not see `no_tile` in the sources?

OK, commit is now on the right branch.

**Review by rc — APPROVED** [review]

**Pull request merged**
