### PR TITLE
Rename extractor to extractor_sfepy

### PR DESCRIPTION
**Pull request by gladk**
extractor.py conflicts with the package python-extractor in Debian.
See [#822435](https://bugs.debian.org/822435)

### CODE REVIEW

**Comment by rc** [comment]
Thank you!

Another possibility, which might be better in future (as also other sfepy scripts have rather generic names), is to install all the main scripts (see ``main_scripts`` in ``setup.py``) as data files only, and leave sfepy-run as a sole script to be installed into dist-packages/.

What do you think? Would that solve https://bugs.debian.org/822435?

**Comment by gladk** [comment]
Sure, it will.

The only problem now is the name conflict in dist-packages so we "workarounded" it by adding
suffix. If extractor.py will be moved out of dist-packages in future sfepy releases, we will just
drop this workaround.

**Comment by rc** [comment]
I can schedule that for 2016.2, to be out probably next week.

**Comment by rc** [comment]
The https://github.com/rc/sfepy/commits/no-symlinks branch (https://github.com/rc/sfepy/commit/530ebc91af6efa04881e0fe38185595fe4d655ab) should do the trick - the main scripts are no longer installed into dist-packages/. (It does also other things, that need to be tested on windows, but that is not relevant here.) Could you verify that?

BTW. there is now a manpage for sfepy - this might be relevant for packaging. It can be built in the doc/ directory using ``make man`` and then viewed using ``man _build/man/sfepy-run.1``

**Comment by gladk** [comment]
Thanks for fixing that. It works just fine.

Is it possible to generate manpage during the sphinx build? 
Also not a relevant to this issue question. Are there any plans to support Python 3?

Regards

**Comment by rc** [comment]
OK, thanks for the testing.

Python 3 is planned (already in #164). Hopefully, @BubuLK will have some spare time to do that in not-so-far future.

What command do you use for building the sphinx docs? 'man' is just another sphinx build target such as 'html' or 'pdf'. It could be made so that e.g. ``python setup.py htmldocs`` built also the man page.

**Comment by rc** [comment]
The 2016.2 release contains the fix, so let us close this.

**Pull request closed without merging**
