### PR TITLE
update d_sd_line_elastic term: new, much faster implementation

### PR DESCRIPTION
**Pull request by vlukes**
- update d_sd_line_elastic term: new, much faster implementation
- remove unused variables in terms_[elastic, diffusion, basic].c

### CODE REVIEW

**Comment by rc** [comment]
Thanks!

```
$ ./run_tests.py --deb tests/test_term_call_modes.py
```

results in 

```
... <-- d_sd_lin_elastic ...
... arg_shapes: {'parameter_mesh_velocity': 'D', 'material': 'S, S', 'parameter_w': 'D', 'parameter_u': 'D'}
... arg_types: ('material', 'parameter_w', 'parameter_u', 'parameter_mesh_velocity')
... args: ['m0.c0', 'p1', 'p2', 'p3']
... call mode: eval
sfepy: setting up dof connectivities...
sfepy: ...done in 0.00 s
*** Error in `python': free(): corrupted unsorted chunks: 0x00000000023f0e20 ***
Aborted (core dumped)
```

Could you check that?

Also fix the indentation and line lengths of d_sd_lin_elastic() C function header in .c and .h files - you can use the same line splitting as you have in terms.pyx.

**Comment by vlukes** [comment]
The indentations and line lengths corrected. Defined reasonable geometry for  d_sd_lin_elastic term, so the test passes now.

**Comment by rc** [comment]
The diff of terms_elastic.c looks like

```
+#define __FUNC__ "d_sd_lin_elastic"
+int32 d_sd_lin_elastic(FMField *out, float64 coef, FMField *gradV,
+		                   FMField *gradU, FMField *gradW, FMField *mtxD,
+                       Mapping *vg)
```

The .h version is also strange - is your editor's C mode working correctly?

The tests now pass, that is OK.

**Comment by vlukes** [comment]
Perhaps something strange in Atom editor,  revised in Emacs.

**Comment by rc** [comment]
Thanks, merging...

**Pull request merged**
