### PR TITLE
Pyvista

### PR DESCRIPTION
**Pull request by vlukes**
New script for visualisation using pyvista.

- customized plots: opacity, warped geometries, selection of subregions, glyphs, ... 
- screenshots with off-screen rendering support
- animations
- VTK/VTU and XDMF input files accepted (including time series)
- independent of SfePy

### CODE REVIEW

**Comment by rc** [comment]
Thanks for the update!

Could you mention the new requirement also in INSTALL and the installation requirements in the docs?

I would change the default colormap to viridis (it seems to be pyvista default), as coolwarm works IMHO well only with data centered around zero(?). Viridis also looks good in BW print.

I wonder about the name of the script - `pview.py` might be confusing (e.g. lots of paraview executables start with 'pv') - what does the 'p' stands for? Should the name point towards pyvista, or VTK and/or FEM post-processing?

It does not matter much now, but in future I would like to make sfepy pip-installable (via entry points), so we need something not too general. Or we just prefix all entry points (the installed scripts) with `sfepy-`.

**Comment by rc** [comment]
When I load a sequence with, for example:
```
python3 ./pview.py cylinder.??.vtk
```
is it possible to switch the view to different time steps?

**Comment by rc** [comment]
BTW. for the animation I needed to install: `pip install --user imageio-ffmpeg`.

**Comment by vlukes** [comment]
You can choose the step by `-s`

	./pview.py cylinder.*.vtk -s 5

or you can specify the step for a given field

	./pview.py cylinder.*.vtk -f bulk_stress:s5

Concerning the script name: what about _pyview_ (PyVista viewer) or _ppview_ (post-proc.)?

**Comment by vlukes** [comment]
> I would change the default colormap to viridis (it seems to be pyvista default), as coolwarm works IMHO well only with data centered around zero(?). Viridis also looks good in BW print.

Viridis is fine! Changed.

> Could you mention the new requirement also in INSTALL and the installation requirements in the docs?

Updated.

**Comment by rc** [comment]
Thanks for the updates! (After we settle on the name, the users' guide figures need to be remade with viridis too.)

For the step, it would be nice (another PR?) to be able to change the step after the view is displayed, e.g. using arrow keys - would that be possible?

Using pview.py with a mesh without results (`python3 ./pview.py meshes/3d/matrix_fiber_rand.vtk`) displays nothing for me, even with -e or -l. Having a single color mesh visible in this case would be nice (another PR, if difficult?).

Ad name, I am thinking in the direction of feview or meshview or sfe(pyview) or solview or resview? Or view_results, ... (Well our other script names are not much descriptive anyway (my "fault"), but maybe this time we can do better?)

**Comment by vlukes** [comment]
> For the step, it would be nice (another PR?) to be able to change the step after the view is displayed, e.g. using arrow keys - would that be possible?

Now, you can change the displayed time step using PgUp and PgDn keys. 

> Using pview.py with a mesh without results (`python3 ./pview.py meshes/3d/matrix_fiber_rand.vtk`) displays nothing for me, even with -e or -l. Having a single color mesh visible in this case would be nice (another PR, if difficult?).

`mat_id` is displayed if there is no other suitable field. 
 
> Ad name, I am thinking in the direction of feview or meshview or sfe(pyview) or solview or resview? Or view_results, ... (Well our other script names are not much descriptive anyway (my "fault"), but maybe this time we can do better?)

I think, that `resview` fits for the script name.

**Comment by rc** [comment]
Thanks! OK, let us use `resview`.

I have proposed a few further fixes [here](https://github.com/rc/sfepy/tree/pyvista), cherry-pick as needed. Otherwise LGTM.

**Comment by vlukes** [comment]
OK

**Comment by rc** [comment]
Thanks! Merging...

**Pull request merged**
