### PR TITLE
update: simplified and unified implementation of some homogenized coe…

### PR DESCRIPTION
**Pull request by vlukes**
Unified implementation of CoefDim, CoefDimDim, CoefSym, CoefSymSym and CoefDimSym.

### CODE REVIEW

**Comment by rc** [comment]
@vlukes, thanks, it looks much simpler that the original version. Could you just remove the newly introduced empty lines, and fix the travis-ci issues?

**Comment by vlukes** [comment]
I forgot the fix for perfusion_micro.py, now it should pass the tests.
Two blank lines between functions are there to meet the PEP8 conventions.

**Comment by rc** [comment]
@vlukes OK, merging.

BTW. check the single failing travis-ci test - there has to be some race condition/read-write if the same file by several processes/? in the homogenization engine, that appears from time to time. Restarting the test usually succeeds. Do you have an idea what causes the problem?

**Comment by vlukes** [comment]
I have no idea what may be wrong in the travis-ci test. We can switch 
off multiprocessing by default.

**Comment by rc** [comment]
@vlukes, to see the actual error:

1. enable travis-ci on your sfepy fork.
2. add ``--raise`` to ``python run_tests.py`` on line 50 of `.travis.yml` (you can remove lines 51-54).
3. commit, push, and check the travis-ci results, until the failure occurs.

**Pull request merged**
