### PR TITLE
fix mesh generators

### PR DESCRIPTION
**Pull request by vlukes**

### CODE REVIEW

**Comment by rc** [comment]
Thanks!

On 02/15/2016 04:11 PM, Vladimir Lukes wrote:
>
> You can view, comment on, or merge this pull request online at:
>
>    https://github.com/sfepy/sfepy/pull/305
>
> -- Commit Summary --
>
>    * fix to_poly_file() in geom_tools.py
>    * fix gen_mesh_from_goem(), remove gen_mesh_from_poly()

There is a typo: gen_mesh_from_goem() -> gen_mesh_from_geom().

**Comment by vlukes** [comment]
The typo has been rectified.

**Comment by rc** [comment]
In the message, yes, but not in the code ;)

**Comment by rc** [comment]
It might be also better to remove the polyfilename argument and use ``tmp_dir = tempfile.mkdtemp()`` for storing the temporary file, what do you think?

**Pull request closed without merging**
